version: '3'
services:
  spark-master:
    image: bde2020/spark-master:2.4.0-hadoop2.7
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - "ENABLE_INIT_DAEMON=false"
    networks:
      - spark
    hostname: spark-master
  spark-worker-1:
    image: bde2020/spark-worker:2.4.0-hadoop2.7
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "ENABLE_INIT_DAEMON=false"
    networks:
      - spark
    hostname: spark-worker

  spark-submit:
    image: maany/spark-submit
    container_name: spark_submit
    depends_on:
      - spark-master
      - spark-worker-1
    networks:
      - spark
    hostname: spark-submit
    environment:
      - "ENABLE_INIT_DAEMON=false"
      - "SPARK_MASTER=spark://spark-master:7077"
    ports:
      - 38999:38999
  # jupyter:
  #   image: jupyter/all-spark-notebooks
  #   container_name: jupyter-notebook
  #   depends_on:
  #     - spark-master
  #     - spark-worker-1
  #   networks:
  #     - spark
  #   hostname: jupyter
  #   ports:
  #     - 10000:8888  
networks:
  spark:
  
